### ISSUE TITLE
Change database to MYSQL 

### ISSUE THREAD

**Issue by mohamed-hussein-1** [sapphireworks/website-generator#18]
change the database to mysql instead of sqlite3

**Comment by abdelrahman-elkady** [comment]
Shouldn't we use **postgerSQL** instead ? @mohamed-hussein-1 

to help us if they needed to deploy on our cute heroku !

**Comment by mohamed-hussein-1** [comment]
we can change it later , for now mysql because it will be easier to work with in the next milestone since we all know the syntax

**Comment by abdelrahman-elkady** [comment]
@mohamed-hussein-1 is this finished ?

if yes please close it
