### ISSUE TITLE
Sequence Diagram

### ISSUE THREAD

**Issue by Amahmoud1994** [sapphireworks/website-generator#19]
Create a branch from the uml-diagrams and name it sequence-diagram to simplify the merging part and to be more organized.
Do not forget to mention the issue number in the commit " #issue_number ".

**Comment by Amahmoud1994** [comment]
Abkr you need to review the diagram after Yassin push it

**Comment by Amahmoud1994** [comment]
@Abkreno  you will find the diagram in the master there was a problem but we will solve it afterwards so review the sequence diagram

**Comment by abkreno** [comment]
done reviewing the diagram all good :+1:

**Comment by Amahmoud1994** [comment]
ok
