### ISSUE TITLE
ERD Diagram

### ISSUE THREAD

**Issue by Amahmoud1994** [sapphireworks/website-generator#21]
Create a branch from the uml-diagrams and name it erd-diagram to simplify the merging part and to be more organized.
Sorry forget to mention the issue number in the commit " #issue_numbe

**Comment by Amahmoud1994** [comment]
Review the erd design Kady

**Comment by Amahmoud1994** [comment]
Sehs review the ERD diagram 
![erd](https://cloud.githubusercontent.com/assets/10798092/6754257/1c59a060-cf24-11e4-8e67-44a680539cfc.jpg)

this is the pic so you won't go to check it there

**Comment by mohamed-hussein-1** [comment]
the relation view has one or more users while template could be viewed by zero users

**Comment by Amahmoud1994** [comment]
You are right

**Comment by Amahmoud1994** [comment]
Done Fixing
