### ISSUE TITLE
Moving the template into rails' views 

### ISSUE THREAD

**Issue by abdelrahman-elkady** [sapphireworks/website-generator#32]
Moving the template into rails' views folder and the assets to it's places in assets folder , in order to follow rails' concepts and conventions

**Comment by abdelrahman-elkady** [comment]
@Abkreno Please review the ... mmmm commits :D , you can just review the scenario and test that everything is working [ There are bugs I know but will be fixed in another issues ] ... 

@mohamed-hussein-1 please review the code [ check the conventions ... ]

**Comment by abkreno** [comment]
reviewed all good :+1:

**Comment by Amahmoud1994** [comment]
If this is Done please close it :D
