### ISSUE TITLE
Template's index page should match the conventions

### ISSUE THREAD

**Issue by abdelrahman-elkady** [sapphireworks/website-generator#47]
Matching the code conventions on the template's index page

**Comment by Amahmoud1994** [comment]
Done reviewing

**Comment by Amahmoud1994** [comment]
You are commenting way too much

**Comment by abdelrahman-elkady** [comment]
@Amahmoud1994 can you give me an example [snippet] ? 

any comment that doesn't match the conventions ??

**Comment by Amahmoud1994** [comment]
No I do not mean that I mean that you are pushing and commit-ing  alot for nothing you could have made the three commits in one only

**Comment by Amahmoud1994** [comment]
But I guess it is for the Process
