### ISSUE TITLE
Create the wireframes for the customization page

### ISSUE THREAD

**Issue by abdelrahman-elkady** [sapphireworks/website-generator#49]

**Comment by smowafy** [comment]
Will the "saving each section separately" thing be related to the customization layout or the editing will be fonts and colors for the whole page at once? @Amahmoud1994 @kadyEG

**Comment by abdelrahman-elkady** [comment]
For now u are just making wireframes , this should be decided after we check how to model our templates 

However , We will use **separate components** rather than **colors for all page** I think .. go with that

**Comment by Amahmoud1994** [comment]
@smowafy The link does not open

**Comment by yassin282** [comment]
@Amahmoud1994  https://moqups.com/sherif.mowafy@gmail.com/uDxbcaSP should works

**Comment by abdelrahman-elkady** [comment]
@smowafy please update it with the latest points we discussed today :hamburger:

**Comment by smowafy** [comment]
@yassin282 take a look and either modify your skeleton or assign me to do it
