### ISSUE TITLE
Create the wireframes for template-2

### ISSUE THREAD

**Issue by abdelrahman-elkady** [sapphireworks/website-generator#50]
Creating the wireframes for template-2 , It should be just a skeleton but it **MUST** be different than the philosophy we used in template-1 [ examples : Use full width , navbar style and place ? , contact us section , .... ]

**Comment by smowafy** [comment]
Okay the philosophy is not quite different, but I'll try to tweak it somehow if people see it's too close to the previous one

**Comment by abdelrahman-elkady** [comment]
ok I mean only try to use full width for example , Add new components like [ carousel , horizontal list ,...]

Those are just examples

**Comment by smowafy** [comment]
The cover is different, takes 100% height, has one of the user's photos blurred with the title and navbar on it, then each section is 100% too, there are some details that I couldn't clearly show in the wireframe

**Comment by abdelrahman-elkady** [comment]
Go on , ask if u need and will discuss after all is finished to edit if we need

**Comment by Amahmoud1994** [comment]
me and @kadyEG  will review

**Comment by Amahmoud1994** [comment]
Done Reviewing

**Comment by abdelrahman-elkady** [comment]
@smowafy @Amahmoud1994 should be closed or there are something missing ?
