### ISSUE TITLE
ERD Discussion

### ISSUE THREAD

**Issue by mohamed-hussein-1** [sapphireworks/website-generator#51]
## Database Look
- every template have an html file inside the project directory
- the html is built using two parts static components and dynamic  ones   (customization)
- static components aren't found inside the database , only inside the html file
- dynamic components exist inside database as class names that you can add to html file and apply the customize desired
- dynamic components exist inside the html wrapped in div or proper element
- another option is to wrap them inside ruby helper methods <escape this point if you can't understand , even me can't understand what i'm saying here>
- for customization there exist something called options which are categories for customization such as fonts , headers .. etc
- every customization belongs to an option (category) and a template
## basic schema < need discussion >

``` sql
template(id,name,thumbnail);
category(id,name);
components(id,className,componentName,template_id,category_id);
```

@Amahmoud1994 @Abkreno

**Comment by Amahmoud1994** [comment]
@Abkreno  @mohamed-hussein-1  We will discuss the schema and then I will design it and you review it

**Comment by Amahmoud1994** [comment]
@mohamed-hussein-1  what do you mean by [category(id,name)] ? and how will it help us?

**Comment by mohamed-hussein-1** [comment]
category to group several customizations so u can choose one for example : 
we have five color palletes ( red - green - blue ....)
so in database 
table category this row
1                palletes
and for every customization of palletes u add it inside the class customizations

**Comment by Amahmoud1994** [comment]
ok I got it

**Comment by abkreno** [comment]
after discussing the overall picture together , so far .. this is the ERD diagram that i have in mind
please review it :
https://drive.google.com/file/d/0B6TDm-J0rYMcb0tQR1RfQUdoaDQ/view?usp=sharing

**Comment by Amahmoud1994** [comment]
@mohamed-hussein-1 what do u think about the suggested ERD by @Abkreno ?
