### ISSUE TITLE
Implementing the skeleton for the Customization page

### ISSUE THREAD

**Issue by Amahmoud1994** [sapphireworks/website-generator#52]
-Please follow the conventions for the html and git.
-Start with the html and then the css.
-Create a branch from the front-end branch and call it customization-page.
-Remember to push on this branch.

**Comment by Amahmoud1994** [comment]
@smowafy  you are assigned to review

**Comment by smowafy** [comment]
@alyezz @yassin282 Regarding the code, everything is fine. However the spacing between the "Preview" and "Publish" buttons can be done in a better way than hard-coding it, let's postpone this.
Please also add documentation according to the conventions mentioned in the wiki.

**Comment by alyezz** [comment]
@kadyEG please review

**Comment by alyezz** [comment]
@kadyEG review

**Comment by abdelrahman-elkady** [comment]
This should be a **view** , that means you shouldn't store the whole `html` document here !

**Comment by Amahmoud1994** [comment]
what do mean @kadyEG  by storing the whole html document here !

**Comment by yassin282** [comment]
@smowafy review

**Comment by yassin282** [comment]
@kadyEG review

**Comment by abdelrahman-elkady** [comment]
This was merged in #78 ... conflicts found and fixed .
