### ISSUE TITLE
implementing the skeleton for template 2

### ISSUE THREAD

**Issue by alyezz** [sapphireworks/website-generator#54]

**Comment by alyezz** [comment]
@smowafy you are assigned to review

**Comment by smowafy** [comment]
@alyezz the skeleton is good, just a note:
The cover image takes 100% width and height, the wireframe is just narrow so this is not really obvious, sorry about that.

Also add the documentation and commit.

**Comment by alyezz** [comment]
@smowafy check it now

**Comment by smowafy** [comment]
@alyezz Okay, now add the documentation

**Comment by smowafy** [comment]
@alyezz add the comment tags accorrding to the documentation or assign me to do it

**Comment by alyezz** [comment]
@smowafy please review
