### ISSUE TITLE
Create the ERD for the proposed database

### ISSUE THREAD

**Issue by abdelrahman-elkady** [sapphireworks/website-generator#55]
After the discussion about the database please create the ERD diagram of the database

**Comment by Amahmoud1994** [comment]
@Abkreno  @mohamed-hussein-1  review the ERD

**Comment by abdelrahman-elkady** [comment]
why are the sections having class-name ?

you also need to reference each component with a palette id

**Comment by Amahmoud1994** [comment]
we agreed that we will have only one css file and we will call the chosen component by its class name , also the relation "has" will contain the super keys [name,color-pallet] from template and [class-name] from the chosen component

**Comment by Amahmoud1994** [comment]
@mohamed-hussein-1 @Abkreno  review the fixed ERD

**Comment by mohamed-hussein-1** [comment]
- adding a name attribute for every entity in the table
- catalogue section contains photos which I think they should be added as entity so the client can choose which photos to appear and in which position

**Comment by abdelrahman-elkady** [comment]
I think also it will be placeholders in the html itself (i.e we store erb in this place , as it will be grabbed from their servers )
