### ISSUE TITLE
creating Database

### ISSUE THREAD

**Issue by mohamed-hussein-1** [sapphireworks/website-generator#61]
creating the database inside rails

**Comment by abdelrahman-elkady** [comment]
@mohamed-hussein-1 Please be careful and make sure to branch out to not brake the current database's based work

**Comment by mohamed-hussein-1** [comment]
@Amahmoud1994  @Abkreno missing three tables for database :
- client
- catalogue
- photos 

need to discuss something with u

**Comment by Amahmoud1994** [comment]
What is wrong with these 3 tables?

**Comment by mohamed-hussein-1** [comment]
not these three tables , but in our ERD , a user chooses a template and the template itself has one of each section , so if user 1 choose template 1 with navbar number 2, all users who choose template 1 will have the same navbar .
