### ISSUE TITLE
Catalogue item in template-1 should have more space 

### ISSUE THREAD

**Issue by abdelrahman-elkady** [sapphireworks/website-generator#63]
Resize the items in carousel in template-1's catalogue to be bigger and more clear !

**Comment by abkreno** [comment]
@kadyEG please review

**Comment by kadyEG** [comment]
why did you modify the database.yml in this commit ?

**Comment by abdelrahman-elkady** [comment]
ok please reset the `database.yml` and modify the sass instead of css

**Comment by abkreno** [comment]
@kadyEG ok i modified the sass now and the database.yml too :+1:  , please review

**Comment by abdelrahman-elkady** [comment]
ok reviewed ad6d5f9ec1eeef498ce3c900f3133ea4601c6245 and 0d22c21cfd100608ac75cfb11ec3c91a24acfb34 and all clear
