### ISSUE TITLE
Fixing the sequence diagram

### ISSUE THREAD

**Issue by Amahmoud1994** [sapphireworks/website-generator#67]
After the new updates we need to change some things in our diagram to fit the new updates.

**Comment by yassin282** [comment]
@sehs review

**Comment by Amahmoud1994** [comment]
@yassin282  we agreed that we will not change the font the client will choose color pallet and a design for every section in the template

**Comment by Amahmoud1994** [comment]
@yassin282 
Give me the link for the website you use to design the sequence so I can fix it
