### ISSUE TITLE
fixing templates table ( adding name column )

### ISSUE THREAD

**Issue by mohamed-hussein-1** [sapphireworks/website-generator#72]
inside the migration `adjustTemplatetable` column name is not created due to syntax error
for those who already did run rake:db:migrate for the database , you should run fix it using these three three commands

``` bash
rails c
ActiveRecord::Migration.add_column :templates, :name, :string
```

this is fix for #61

**Comment by mohamed-hussein-1** [comment]
@yassin282 review this

**Comment by yassin282** [comment]
reviewed
