### ISSUE TITLE
Colorize template-1

### ISSUE THREAD

**Issue by abdelrahman-elkady** [sapphireworks/website-generator#85]
Add some colorization ( preferably in a base variable(s) in sass )  to build up on template-1 , please choose only one theme and colorize the whole template (text,bg,carousel,hover,...) for now

**Comment by smowafy** [comment]
@kadyEG you are assigned to review, these are just initial modification, further work should be done on the template

**Comment by abdelrahman-elkady** [comment]
This was updated in details in sprint-2 .. closing
