### ISSUE TITLE
Transfer template 2 to the app folder

### ISSUE THREAD

**Issue by abdelrahman-elkady** [sapphireworks/website-generator#86]
Add template 2 to the app folder with all the appropriate transitions needed for js , stylesheets (sass conversion needed ) ... please don't modify other files ( index.html.erb , any stylesheets belongs to other templates , ... )

**Comment by alyezz** [comment]
@kadyEG  is the structure of the folders correct so far? i didn't test yet (the template itself)

**Comment by abdelrahman-elkady** [comment]
I think somehow yes , except the sass thing and the images and the js

**Comment by abdelrahman-elkady** [comment]
More updates in #102
