### ISSUE TITLE
Create UML and class diagrams

### ISSUE THREAD

**Issue by abdelrahman-elkady** [sapphireworks/website-generator#9]
Please check the diagrams needed and add them to a new directory in the project

**Comment by Amahmoud1994** [comment]
![uml diagram](https://cloud.githubusercontent.com/assets/10798092/6748385/8eafc2b6-ceed-11e4-87e5-03844d734803.png)

**Comment by Amahmoud1994** [comment]
Adding the UML diagram in the branch uml-diagrams

**Comment by Amahmoud1994** [comment]
Done creating the Diagrams and merging them all in uml-diagrams branch
